#!/bin/bash
echo "Running Setup from $(pwd) with arguments $*"

source "/data/SetupHelper/CommonResources"
BASE_DIR=/data/CHC1203-canbus

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	# display initial message
	echo
	echo "CHC1203-canbus"
	
	standardActionPrompt
fi

function cleanup ()
{
	echo cleanup
}

#### install code goes here
if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "Installing CHC1203-canbus"
	
#    updateFileSets
	opkg install python3-pip python3-can

	installService CHC1203-canbus
	cleanup
fi


#### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
	logMessage "Uninstalling CHC1203-canbus"
	removeService CHC1203-canbus
fi

endScript
