#!/bin/bash
exec 2>&1

# sleep 30
# exit

# canInterfaceName=vcan2
# ip link set up $canInterfaceName

if [[ $# -eq 0 ]]; then
    basedir=/data/CHC1203-canbus
else #This is the dev version, running from the local directory
    basedir=$(dirname $0)/..
fi

cd $basedir
env PYTHONPATH=$PWD python3 $basedir/quickbus-ecan.py -i 192.168.4.10 -p 8882 -v -v

