#!/bin/bash
exec 2>&1

# sleep 30
# exit

canInterfaceName=vcan2

modprobe vcan
ip link add dev $canInterfaceName type vcan
ip link set up $canInterfaceName

if [[ $# -eq 0 ]]; then
    basedir=/data/CHC1203-canbus
else #This is the dev version, running from the local directory
    basedir=$(dirname $0)/..
fi

cd $basedir
env PYTHONPATH=python-can-develop/:typing_extensions-4.2.0/src python3 $basedir/quickbus-ecan.py -c $canInterfaceName

